name: Fluffy
version: 1.0-SNAPSHOT
main: me.antritus.astral.fluffycombat.FluffyCombat
api-version: '1.20'
authors: [antritus]

dependencies:
  server:
    Citizens:
      load: BEFORE
      required: false
      join-classpath: true
    Wormhole:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
